name: Scheduled Cron Job

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run cron job
        run: |
          curl -X POST https://channel-check.vercel.app/api/report1
